In [2]:
import numpy as np
# create array using array function
data1=np.array([1,3,9,12,18])
# data1 + data1
data1

array([ 1,  3,  9, 12, 18])

In [18]:
print(data1.astype(np.int32).dtype)
# print(data1.dtype)

int32


In [11]:
print(np.zeros((2,3)))
print(np.ones((2,4)))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
print(np.random.randint(100, size=(6, 3)))

[[ 5 15 83]
 [33  5 98]
 [13 45 75]
 [60 18 77]
 [10 76 95]
 [61 12  2]]


In [45]:
data2=np.array([[ 5, 15, 83], [33,  5 ,98] ,[13, 45, 75], [60, 18, 77] ,[10, 76, 95], [61, 12,  2]])
data2[0,2]=data2[0,2]**2
data2


array([[   5,   15, 6889],
       [  33,    5,   98],
       [  13,   45,   75],
       [  60,   18,   77],
       [  10,   76,   95],
       [  61,   12,    2]])

In [15]:
data1


array([1, 2, 3], dtype=int32)

In [29]:
subjects = np.array([
    ['ML', 'OS', 'CCN'],
    ['OS', 'AI', 'MP'],
    ['CCN', 'ML', 'AI']
])
mask = (subjects == 'ML') | (subjects == 'AI')
subjects_masked = np.where(mask, subjects, 0)


DTypePromotionError: The DType <class 'numpy.dtypes.StrDType'> could not be promoted by <class 'numpy.dtypes._PyLongDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyLongDType'>)

In [34]:
Subjects = np.array([["ML","OS","CCN"],["OS","AI","MP"],["CCN","ML","AI"]])
# numpy built-in method
# newSubjects = np.isin(Subjects,["ML","AI"],invert=True)
# Subjects[newSubjects] = 0
# Subjects
# Boolean Indexing Method
Subjects[(Subjects != "ML") & (Subjects != "AI")] = 0
Subjects

array([['ML', '0', '0'],
       ['0', 'AI', '0'],
       ['0', 'ML', 'AI']], dtype='<U3')

In [37]:
data3 = np.array([['7', '6'],
                  ['5', '4'],
                  ['3', '2']])
data4 = np.array([[11, 52, 20, 50],
                  [34, 61, 43, 17]])

data2_transposed = data2.T
data3_transposed = data3.T
data4_transposed = data4.T
print(data2_transposed,'\n',data3_transposed,data4_transposed)

[[   5   33   13   60   10   61]
 [  15    5   45   18   76   12]
 [6889   98   75   77   95    2]] 
 [['7' '5' '3']
 ['6' '4' '2']] [[11 34]
 [52 61]
 [20 43]
 [50 17]]


In [46]:
mdata2=data2 - data2.mean(axis=0)
mdata2


array([[-2.53333333e+01, -1.35000000e+01,  5.68300000e+03],
       [ 2.66666667e+00, -2.35000000e+01, -1.10800000e+03],
       [-1.73333333e+01,  1.65000000e+01, -1.13100000e+03],
       [ 2.96666667e+01, -1.05000000e+01, -1.12900000e+03],
       [-2.03333333e+01,  4.75000000e+01, -1.11100000e+03],
       [ 3.06666667e+01, -1.65000000e+01, -1.20400000e+03]])

In [48]:
meanData2 = data2.mean(0)
demeanData2 = data2 - meanData2
demeanData2
# data2


array([[-2.53333333e+01, -1.35000000e+01,  5.68300000e+03],
       [ 2.66666667e+00, -2.35000000e+01, -1.10800000e+03],
       [-1.73333333e+01,  1.65000000e+01, -1.13100000e+03],
       [ 2.96666667e+01, -1.05000000e+01, -1.12900000e+03],
       [-2.03333333e+01,  4.75000000e+01, -1.11100000e+03],
       [ 3.06666667e+01, -1.65000000e+01, -1.20400000e+03]])

In [3]:
student_scores = np.array([
    [60, 70, 50],  # Subject1
    [40, 60, 80],  # Subject2
    [70, 55, 65]   # Subject3
])

In [4]:
print( student_scores.max(axis=1))

[70 80 70]
