In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

from sklearn import metrics 
from sklearn.metrics import confusion_matrix, classification_report 


In [3]:
from sklearn import datasets 

# Load data with only two classes and two features 
iris = datasets.load_iris()  

In [10]:
X= iris.data

In [12]:
Y= iris.target

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() 
features_standardized = scaler.fit_transform(X) 

In [18]:
from sklearn.svm import SVC 
svc_linear = SVC(kernel="linear", random_state=0, C=1) 

# Train model 
model_linear=svc_linear.fit(features_standardized,Y)

In [19]:

target_pred_linear = model_linear.predict(features_standardized) 
target_pred_linear

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
# Printing results
print("The accuracy is "+str(metrics.accuracy_score(Y,target_pred_linear)*100)+"%") 
print(confusion_matrix(Y,target_pred_linear))  

The accuracy is 96.66666666666667%
[[50  0  0]
 [ 0 46  4]
 [ 0  1 49]]


In [22]:
svc_rbf = SVC(kernel="rbf", random_state=0, gamma=1, C=1) 

# Train the classifier 
model_svc=svc_rbf.fit(features_standardized,Y) 

In [24]:
target_pred_rbf = model_svc.predict(features_standardized) 
target_pred_rbf

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
# Printing results
print("The accuracy is "+str(metrics.accuracy_score(Y,target_pred_rbf)*100)+"%") 
print(confusion_matrix(Y,target_pred_rbf))  

The accuracy is 98.66666666666667%
[[50  0  0]
 [ 0 49  1]
 [ 0  1 49]]


In [27]:
svc_polynomial = SVC(kernel="poly", random_state=0, gamma=1, C=1) 

# Train the classifier 
model_polynomial=svc_polynomial.fit(features_standardized,Y) 

In [28]:
target_pred_poly = model_polynomial.predict(features_standardized) 
target_pred_poly

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
# Printing results
print("The accuracy is "+str(metrics.accuracy_score(Y,target_pred_poly)*100)+"%") 
print(confusion_matrix(Y,target_pred_poly))  

The accuracy is 98.66666666666667%
[[50  0  0]
 [ 0 49  1]
 [ 0  1 49]]
